name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Publish to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: itjobmarketanalytics/telegram-notification-service
          registry: docker.io
          tags: ${BRANCH_NAME}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trigger repo
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: it-job-market-analytics
          repo: compose-stack
          ref: prod
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: deploy-runners.yaml
          client_payload: '{}'
          wait_interval: 11
          trigger_workflow: true
          wait_workflow: true
          propagate_failure: true