### login
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "newUser2",
  "password": "123456"
}
> {% client.global.set("auth_token", response.body.accessToken); %}
