### get user Subscriptions
GET http://localhost:8080/subscriptions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### get all available subscriptions
GET http://localhost:8080/subscriptions/allAvailable
Content-Type: application/json


### add subscriptions query
POST http://localhost:8080/subscriptions/java
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### remove subscriptions query
DELETE http://localhost:8080/subscriptions/java
Content-Type: application/json
Authorization: Bearer {{auth_token}}